# Change these first
owner: Yellow-Team-Millerslab # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Mpix
    url: https://www.mpix.com
  - name: Mpix-api
    url: https://api-production.mpix.com/api/v1.0/systeminfo
  - name: Mpix-cms-assets
    url: https://cms-assets.mpix.com/api/assets/mpix/bbadd302-7b1f-48ea-9596-2938e0775880/happy-quokka.jpg?version=0
  - name: Mpix-2-print
    url: https://www.mpix.com/products/prints
  - name: Mpix-2-image
    url: https://images.mpix.com/ver/m2.5.0/98x47/logo.mpng
  - name: Millerslab.com
    url: https://www.millerslab.com

assignees: # Users to assign downtime issues
  - Sam-Lin-MillersLab
  - nicholasconfer

status-website:
  publish: true
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.millerslab.com
  # baseUrl: /your-repo-name
  logoUrl: https://cms-assets.mpix.com/api/assets/mpix/4c6f7b50-32c1-4c60-b542-3e239d380ae7/logo-main.jpg?version=0
  name: ""
  introTitle: Millerslab Public Web Service Uptime
  introMessage: "Powered by Upptime"
  navbar:
    - title: Response Time
      href: /
    - title: Uptime
      href: https://statuspage.freshping.io/61959-Millerslab
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # Upptime also supports notifications, assigning issues, and more
  # See https://upptime.js.org/docs/configuration
